name: shelf_azure_application_insights
description: A Shelf middleware to send request data to Azure Application Insights.
version: 0.0.2
repository: https://github.com/evoleen/shelf_azure_application_insights
environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  azure_application_insights: ^4.0.1
  http: ^1.2.2
  shelf: ^1.4.2
dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
